#!/bin/bash
host="$1"
set -e

if [ -e /etc/sysinfo.conf ];then
   . /etc/sysinfo.conf
fi

if [ -z "$host" ]; then
   host=$(hostname)
fi

if [ -z "$email_recipient" ]; then
   email_recipient="admin@kwundsam.de"
fi

statedir=/var/spool/checkmail-sysinfo
mkdir -p $statedir/$host
cd $statedir/$host

rsync -e ssh -a root@$host:/var/sysinfo/ new/
grep  -l -R '@IgnoreForMail' new | xargs --no-run-if-empty -d $"\n" rm

if [ -e current ]; then
   if [ -e old ]; then
      rm -rf old
   fi
   mv current old
else
   mkdir -p old
fi
mv new current

if diff -rN old current >/dev/null; then
	# identical
	true
else
	diff -u -N -r old current | mail -s "[sysinfo] Configuration changes on host $host" $email_recipient
fi
