#!/bin/bash
vgdisplay=$(which vgcfgbackup)
if [ $? -gt 0 ]; then
	echo "LVM not installed"
	exit 0
fi

echo "==============================================================================================="
echo "vgcfgbackup:"

tmpfile=$(mktemp)
vgcfgbackup -f $tmpfile
cat $tmpfile
rm $tmpfile
