#!/bin/bash
vgdisplay=$(which vgcfgbackup)
if [ $? -gt 0 ]; then
	echo "LVM not installed"
	exit 0
fi

echo "==============================================================================================="
echo "vgcfgbackup:"

set -e
tmpdir=$(mktemp -d)
cd $tmpdir
vgcfgbackup -f '%s.cfg'
cat *.cfg
cd /
rm -rf $tmpdir
