#!/bin/bash

netstat -pltn | perl -pe 's{\d+/([^ \t]+)[ \t]*$}{$1}' | sort -n
netstat -plun | perl -pe 's{\d+/([^ \t]+)[ \t]*$}{$1}' | perl -ane 'unless($F[3] =~ /.*:(\d+)$/ && $1 > 1023) { print $_ }' | sort -n
