#!/bin/bash

excludefile=/etc/sysinfo/sys-lsmod/exclude-modules 

list_modules() {
   lsmod | cut -d ' ' -f 1 | sort
}

if [ -e $excludefile ]; then
	list_modules | grep -v -E -x -f $excludefile
else
	list_modules
fi
